#!/bin/sh
#
# ESG Federation download script
#
# Template version: 0.3
# Generated by Gateway: ESG-PCMDI
#


##############################################################################

download() {    
    
    wget -c -O 'hfss_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc' 'http://dap.cccma.uvic.ca/thredds/fileServer/esg_dataroot/AR5/CMIP5/output/CCCma/CanCM4/rcp45/mon/atmos/hfss/r1i1p1/hfss_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc?gateway=ESG-PCMDI&authzToken=c6b6fa9f-f3c8-4516-b9c7-5e516af4b913'
    wget -c -O 'rlus_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc' 'http://dap.cccma.uvic.ca/thredds/fileServer/esg_dataroot/AR5/CMIP5/output/CCCma/CanCM4/rcp45/mon/atmos/rlus/r1i1p1/rlus_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc?gateway=ESG-PCMDI&authzToken=9ccf165d-53ce-4f1a-8164-96026d51679d'
    wget -c -O 'tas_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc' 'http://dap.cccma.uvic.ca/thredds/fileServer/esg_dataroot/AR5/CMIP5/output/CCCma/CanCM4/rcp45/mon/atmos/tas/r1i1p1/tas_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc?gateway=ESG-PCMDI&authzToken=b7101740-5fd4-4509-b46b-7587bc516e87'
    wget -c -O 'pr_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc' 'http://dap.cccma.uvic.ca/thredds/fileServer/esg_dataroot/AR5/CMIP5/output/CCCma/CanCM4/rcp45/mon/atmos/pr/r1i1p1/pr_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc?gateway=ESG-PCMDI&authzToken=47e307a8-3454-466e-b951-e69f9e0b0bcf'
    wget -c -O 'psl_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc' 'http://dap.cccma.uvic.ca/thredds/fileServer/esg_dataroot/AR5/CMIP5/output/CCCma/CanCM4/rcp45/mon/atmos/psl/r1i1p1/psl_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc?gateway=ESG-PCMDI&authzToken=9e686c26-b2af-4d63-8d18-a3165c38a1c7'
    wget -c -O 'rsds_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc' 'http://dap.cccma.uvic.ca/thredds/fileServer/esg_dataroot/AR5/CMIP5/output/CCCma/CanCM4/rcp45/mon/atmos/rsds/r1i1p1/rsds_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc?gateway=ESG-PCMDI&authzToken=a1f507b6-106e-4510-bc00-7b2ed617e5e5'
    wget -c -O 'hfls_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc' 'http://dap.cccma.uvic.ca/thredds/fileServer/esg_dataroot/AR5/CMIP5/output/CCCma/CanCM4/rcp45/mon/atmos/hfls/r1i1p1/hfls_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc?gateway=ESG-PCMDI&authzToken=5b2becf1-17db-4f49-a20b-3a282211c230'
    wget -c -O 'rsus_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc' 'http://dap.cccma.uvic.ca/thredds/fileServer/esg_dataroot/AR5/CMIP5/output/CCCma/CanCM4/rcp45/mon/atmos/rsus/r1i1p1/rsus_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc?gateway=ESG-PCMDI&authzToken=29312454-cfbf-4ac2-9a42-8b00d7ce958e'
    wget -c -O 'rlds_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc' 'http://dap.cccma.uvic.ca/thredds/fileServer/esg_dataroot/AR5/CMIP5/output/CCCma/CanCM4/rcp45/mon/atmos/rlds/r1i1p1/rlds_Amon_CanCM4_rcp45_r1i1p1_200601-203512.nc?gateway=ESG-PCMDI&authzToken=da7df4a1-0ed3-46d9-8c24-316a3a2df170'

}


#
# MAIN
#
download

